version: "3.7"

services:
  # Ambiente de Teste (Staging)
  web-staging:
    build: .
    environment:
      NODE_ENV: development
      MONGODB_URI: mongodb://mongo-staging:27017/nodegoat
    command: sh -c "until nc -z -w 2 mongo-staging 27017 && echo 'mongo-staging is ready for connections' && node artifacts/db-reset.js && npm start; do sleep 2; done"
    ports:
      - "4001:4000"  # Porta externa diferente para evitar conflitos

  mongo-staging:
    image: mongo:4.4
    user: mongodb
    expose:
      - 27017

  # Ambiente de Produção
  web-production:
    build: .
    environment:
      NODE_ENV: production
      MONGODB_URI: mongodb://mongo-production:27017/nodegoat
    command: sh -c "until nc -z -w 2 mongo-production 27017 && echo 'mongo-production is ready for connections' && node artifacts/db-reset.js && npm start; do sleep 2; done"
    ports:
      - "4002:4000"  # Porta externa diferente para evitar conflitos

  mongo-production:
    image: mongo:4.4
    user: mongodb
    expose:
      - 27017
